#version: "3.10"
services:
  alpr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    restart: always


#    environment:
#      FLASK_DEBUG: "true"
#networks:
#  default:
#    external:
#      name: nostradamus-network